### ISSUE TITLE
Monitor requires curses (not installed)

### ISSUE THREAD

**Issue by DanAtkinson** [m3talstorm/foe-bot#5]
Hi there,

I had a quick play and found that the `main.py` script works without issue.

However, when I ran the `monitor.py` script, I got an error that `curses` wasn't installed.

I grabbed curses from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/) and installed it with `python -m pip install curses-2.2-cp27-none-win_amd64.whl`.

    Processing d:\temp\curses-2.2-cp27-none-win_amd64.whl
    Installing collected packages: curses
    Successfully installed curses-2.2

Now, when I run `python monitor.py` I get the following:

    Traceback (most recent call last):
      File "monitor.py", line 32, in <module>
        wrapper(main)
      File "C:\Python27\lib\curses\wrapper.py", line 43, in wrapper
        return func(stdscr, *args, **kwds)
      File "monitor.py", line 28, in main
        monitor.run()
      File "D:\Github\foe-bot\foe\monitors\monitor.py", line 66, in run
        self.render()
      File "D:\Github\foe-bot\foe\monitors\building_monitor.py", line 77, in render
        colour)
    _curses.error: addstr() returned ERR

Any pointers would be much appreciated. Maybe you have a different `curses` installed?

**Comment by m3talstorm** [comment]
Hi @DanAtkinson Sorry I didn't see your message, I only just realized that I didn't have notifications (watching) turned on for this repo :(

From my understanding [curses](https://docs.python.org/2/library/curses.html) is part of Python.

> _curses.error: addstr() returned ERR

Is from your window/terminal/screen being to small (vertically) to print the text, either make your window/terminal bigger or look [here](https://github.com/m3talstorm/foe-bot/blob/master/foe/monitors/building_monitor.py#L63) and reduce the number of buildings it displays at once.

If you have and actual fix rather than a workaround feel free to submit a PR.

**Comment by DanAtkinson** [comment]
Yep, that'll be it. I increased the terminal size (I use [Cmder](http://cmder.net/)) and it ran. I think a [simple check](https://gist.github.com/jtriley/1108174) for the terminal size might help.

**Comment by DanAtkinson** [comment]
Also, as an aside, curses definitely wasn't installed and I had to install that before I got the error message in my first comment.

**Comment by sammeowww** [comment]
I've experienced similar problem, as my screen is not wide enough, change the width solved the problem
File: `foe/monitors/monitor.py`
```
class Monitor(object):
    SEPERATOR = 140 * '-'
```
Change to
```
class Monitor(object):
    SEPERATOR = 115 * '-'
```
